kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: ["extensions"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: ["extensions"]
  resources: ["deployments/scale"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]
- apiGroups: ["apps"]
  resources: ["statefulsets/scale"]
  verbs: ["get", "list", "delete", "update", "create", "apply", "patch"]